backend CI/CD 2

diff --git a/.github/workflows/cd_backend.yml b/.github/workflows/cd_backend.yml
--- a/.github/workflows/cd_backend.yml
+++ b/.github/workflows/cd_backend.yml
@@ -23,4 +23,24 @@ jobs:
           push: true
           tags: sarthakjazz/todo-app-backend:${{ github.sha }}
 
+      - name: Deploy to AWS Ubuntu Server
+        run: |
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
+          chmod 600 ~/ssh_key
+          
+          # Stop existing container
+          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker stop backend || true"
+          
+          # Remove existing container
+          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker rm backend || true"
+          
+          # Pull latest image
+          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker pull sarthakjazz/todo-app-backend:${{ github.sha }}"
+          
+          # Run new container
+          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker run -d --name backend -p 3001:3001 sarthakjazz/todo-app-backend:${{ github.sha }}"
+          
+          # Clean up old images
+          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker image prune -f"
+
     
diff --git a/.github/workflows/cd_websocket.yml b/.github/workflows/cd_websocket.yml
--- a/.github/workflows/cd_websocket.yml
+++ b/.github/workflows/cd_websocket.yml
@@ -23,22 +23,22 @@ jobs:
           push: true
           tags: sarthakjazz/todo-app-websocket:${{ github.sha }}
 
-      - name: Deploy to AWS Ubuntu Server
-        run: |
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
-          chmod 600 ~/ssh_key
+      # - name: Deploy to AWS Ubuntu Server
+      #   run: |
+      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
+      #     chmod 600 ~/ssh_key
           
-          # Stop existing container
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker stop websocket || true"
+      #     # Stop existing container
+      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker stop websocket || true"
           
-          # Remove existing container
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker rm websocket || true"
+      #     # Remove existing container
+      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker rm websocket || true"
           
-          # Pull latest image
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker pull sarthakjazz/todo-app-websocket:${{ github.sha }}"
+      #     # Pull latest image
+      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker pull sarthakjazz/todo-app-websocket:${{ github.sha }}"
           
-          # Run new container
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker run -d --name websocket -p 8080:8080 sarthakjazz/todo-app-websocket:${{ github.sha }}"
+      #     # Run new container
+      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker run -d --name websocket -p 8080:8080 sarthakjazz/todo-app-websocket:${{ github.sha }}"
           
-          # Clean up old images
-          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker image prune -f"
+      #     # Clean up old images
+      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker image prune -f"
